name: Build

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
      - run: npm install --legacy-peer-deps
      - run: cp ./src/DB/config.template.ts ./src/DB/config.ts
      - run: npm run build
      - run: echo Build success
